services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - ORG_ID=aprovan
      - PROJECT_ID=zolvery
      - ENVIRONMENT=dev
      - PERSISTENCE=1
      - SERVICES=s3,sqs,dynamodb,sns
      - REGION_SHORT_CODE=use2
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=zolvery
      - AWS_SECRET_ACCESS_KEY=zolvery
      - AWS_ENDPOINT_URL=http://localhost:4566
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - localstack_data://var/lib/localstack/state
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    ports:
      - "3001:3000"
      - "4317:4317"
    volumes:
      - lgtm_data:/data

volumes:
  localstack_data:
  lgtm_data:
