services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - PERSISTENCE=1
      - SERVICES=s3,sqs,dynamodb
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-data:/tmp/localstack/data

volumes:
  localstack-data:
