services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - PERSISTENCE=1
      - SERVICES=s3,sqs,dynamodb
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack/data
      - './scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'

volumes:
  localstack_data:
